name: PR Test

on:
  push:
    branches-ignore:
      - test-workflow
  pull_request:
    branches: # pull request target is test-workflow
      - test-workflow
jobs:
  guard:
    name: POC Merge Guard
    runs-on: ubuntu-latest
    steps:
      - name: Check for Proof of Concept
        shell: bash
        run: |
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github = ${{ github }}"
          exit 1
